name: Enhancement
description: Track enhancement tasks including proof of concept, new features, and tech debt removal
title: "[ENHANCEMENT] "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Enhancement Task
        Use this template for tracking enhancement work such as proof of concepts, building new features, or removing technical debt.
  
  - type: dropdown
    id: enhancement-type
    attributes:
      label: Enhancement Type
      description: What type of enhancement is this?
      options:
        - Proof of Concept (POC)
        - New Feature
        - Tech Debt Removal
        - Performance Improvement
        - Refactoring
        - Other Enhancement
    validations:
      required: true
  
  - type: input
    id: title
    attributes:
      label: Enhancement Title
      description: Brief description of the enhancement
      placeholder: e.g., "POC - Evaluate GraphQL for API layer" or "Remove deprecated authentication library"
    validations:
      required: true
  
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide details about this enhancement
      placeholder: Describe what needs to be done and why this enhancement is needed
    validations:
      required: true
  
  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement / Motivation
      description: What problem does this enhancement solve? Why is it needed?
      placeholder: Explain the current issue or opportunity that this enhancement addresses
    validations:
      required: false
  
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How do you plan to implement this enhancement?
      placeholder: Describe the technical approach, tools, or methods to be used
    validations:
      required: false
  
  - type: textarea
    id: success-criteria
    attributes:
      label: Success Criteria / Acceptance Criteria
      description: How will we know this enhancement is complete and successful?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: false
  
  - type: textarea
    id: technical-details
    attributes:
      label: Technical Details
      description: Any technical specifications, dependencies, or considerations
      placeholder: |
        - Technologies/Libraries: 
        - Dependencies: 
        - Breaking Changes: 
        - Migration Required: 
    validations:
      required: false
  
  - type: textarea
    id: checklist
    attributes:
      label: Implementation Checklist
      description: List the steps needed to complete this enhancement
      placeholder: |
        - [ ] Research and design
        - [ ] Implementation
        - [ ] Testing
        - [ ] Documentation
        - [ ] Code review
        - [ ] Deployment
    validations:
      required: false
  
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: What is the priority level?
      options:
        - Low
        - Medium
        - High
        - Urgent
    validations:
      required: false
  
  - type: dropdown
    id: effort
    attributes:
      label: Estimated Effort
      description: How much effort will this require?
      options:
        - Small (< 1 day)
        - Medium (1-3 days)
        - Large (1-2 weeks)
        - Extra Large (2+ weeks)
    validations:
      required: false
  
  - type: input
    id: target-date
    attributes:
      label: Target Completion Date
      description: When should this be completed?
      placeholder: e.g., "2025-11-30" or "End of Q4 2025"
    validations:
      required: false
  
  - type: textarea
    id: risks
    attributes:
      label: Risks & Considerations
      description: Any potential risks, blockers, or considerations
      placeholder: List any risks, dependencies on other work, or potential blockers
    validations:
      required: false
  
  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      description: Any additional context, links, or information
      placeholder: Add any relevant links, references, diagrams, or context
    validations:
      required: false
