# Team Dashboard Configuration

[issues-api]
# Only show results that were last updated after the given time. 
since = "2025-07-01T00:00:00Z"  # ISO 8601 format

# Work Type Labels Mapping
# Only 'project' and 'enhancement' labels are tracked
# Everything else is classified as 'other'
[work-types]
project = ["project"]
enhancement = ["enhancement"]

# Special Status Labels
# These labels can be combined with project/enhancement
[status-labels]
blocked = "blocked"     # Work is blocked, needs manager intervention
win = "win"            # High value-add work

# Chart Colors (hex codes without #)
[colors]
project = "02cecb"      # Teal
enhancement = "7209b7"  # Purple
other = "6b7280"        # Gray
blocked = "ef4444"      # Red (for blocked indicator)
win = "ffbf00"          # Gold (for win indicator)

# Team Members
# Map GitHub usernames to preferred display names
[[member]]
git-name = "vthai-wtg"
preferred-name = "Vinh"
[[member]]
git-name = "v-thai"
preferred-name = "GithubMcGitface"
